export const books = [
  {id: 1, book: 'Gênesis'},
  {id: 2, book: 'Êxodo'},
  {id: 3, book: 'Levítico'},
  {id: 4, book: 'Números'},
  {id: 5, book: 'Deuteronômio'},
  {id: 6, book: 'Josué'},
  {id: 7, book: 'Juízes'},
  {id: 8, book: 'Rute'},
  {id: 9, book: '1 Samuel'},
  {id: 10, book: '2 Samuel'},
  {id: 11, book: '1 Reis'},
  {id: 12, book: '2 Reis'},
  {id: 13, book: '1 Crônicas'},
  {id: 14, book: '2 Crônicas'},
  {id: 15, book: 'Esdras'},
  {id: 16, book: 'Neemias'},
  {id: 17, book: 'Ester'},
  {id: 18, book: 'Jó'},
  {id: 19, book: 'Salmos'},
  {id: 20, book: 'Provérbios'},
  {id: 21, book: 'Eclesiastes'},
  {id: 22, book: 'Cânticos'},
  {id: 23, book: 'Isaías'},
  {id: 24, book: 'Jeremias'},
  {id: 25, book: 'Lamentações de Jeremias'},
  {id: 26, book: 'Ezequiel'},
  {id: 27, book: 'Daniel'},
  {id: 28, book: 'Oséias'},
  {id: 29, book: 'Joel'},
  {id: 30, book: 'Amós'},
  {id: 31, book: 'Obadias'},
  {id: 32, book: 'Jonas'},
  {id: 33, book: 'Miquéias'},
  {id: 34, book: 'Naum'},
  {id: 35, book: 'Habacuque'},
  {id: 36, book: 'Sofonias'},
  {id: 37, book: 'Ageu'},
  {id: 38, book: 'Zacarias'},
  {id: 39, book: 'Malaquias'},
  {id: 40, book: 'Mateus'},
  {id: 41, book: 'Marcos'},
  {id: 42, book: 'Lucas'},
  {id: 43, book: 'João'},
  {id: 44, book: 'Atos'},
  {id: 45, book: 'Romanos'},
  {id: 46, book: '1 Coríntios'},
  {id: 47, book: '2 Coríntios'},
  {id: 48, book: 'Gálatas'},
  {id: 49, book: 'Efésios'},
  {id: 50, book: 'Filipenses'},
  {id: 51, book: 'Colossenses'},
  {id: 52, book: '1 Tessalonicenses'},
  {id: 53, book: '2 Tessalonicenses'},
  {id: 54, book: '1 Timóteo'},
  {id: 55, book: '2 Timóteo'},
  {id: 56, book: 'Tito'},
  {id: 57, book: 'Filemom'},
  {id: 58, book: 'Hebreus'},
  {id: 59, book: 'Tiago'},
  {id: 60, book: '1 Pedro'},
  {id: 61, book: '2 Pedro'},
  {id: 62, book: '1 João'},
  {id: 63, book: '2 João'},
  {id: 64, book: '3 João'},
  {id: 65, book: 'Judas'},
  {id: 66, book: 'Apocalipse'}
]